### ISSUE TITLE
Should we introduce subclasses of oban:association?

### ISSUE THREAD

**Issue by cmungall** [jamesmalone/OBAN#3]
We can imagine

 * PhenotypeAssociation
    * GenePhenotypeAssociation
    * DiseasePhenotypeAssociation

etc

the annoying thing is it would be hard to classify into these deeper classes automatically using standard owl reasoning, but perhaps this isn't an issue.

Thoughts?

**Comment by jamesmalone** [comment]
We'd originally envisioned only two types of association - positive (is associated with) and negative (not associated with). The first would be used when there is a positive correlation and the latter when there is a definite non-association between something, i.e. negative evidence. I guess question is whether you can just infer the above from the subject - object or whether there is a reason to assert this for e.g. efficient querying? Was that your thinking?

**Comment by helenp** [comment]
Also VariantPhenotypeAssociation, not all associations are genic, much of the GWAS is not, different variants have different phenotypes.
And MeasurementPhenotypeAssociation

**Comment by cmungall** [comment]
I like having separate classes for Pos and Neg (mirroring the OWLAPI ABox assertions). It's really important to keep these separate -- people ignore qualifier fields, and having distinct classes is an easier way to distinguish the different semantics.

So I see if we then went with my suggestion of also including classes for datatype we would send up with a cross-product of `{+,-} x {T1,T2,...}`. Which is doable but awkward and would require you to do reasoning or graph traversal to get the semantics. Or you could do two separate rdf:type assertions, but this still is a bit odd. So I don't think my original suggestion was such a good idea!

The same thing could be achieved without overloading rdf:type. We could invent a property like 'category' that could link to some hierarchy of classes.
